### PR TITLE
docs(contributing): replace references to "tell-me" with "metiers-numeriques"

### PR DESCRIPTION
**Pull request by dimitri-bourreau**
This PR follows #264.
I did not update the line 32.

@ivangabriele can you tell me if this PR is well done since you merged #264?

### CODE REVIEW

**Comment by ivangabriele** [comment]
Your PR is almost perfect, you respect [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) and make small PRs which makes them easy to review :).

You should also sign your commits for security (so that I know you commits are really authored by yourself and not someone else pretending to be "you"): https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

It can seem like a hassle at first glance but you can automate the commit signing process as explained in the "Tips" box [there](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

Signed commits are mandatory on any "safe-aware" repository and I had to disable them temporarily on this one to allow your PR to merged 😅.

They look like that once you've successfully set them up:

image

**Comment by ivangabriele** [comment]
I admit I didn't recheck `CONTRIBUTING.md` content for a while, so don't hesitate to ask me anything that doesn't work or is not clear enough ^^.

**Comment by dimitri-bourreau** [comment]
@ivangabriele ho you're right! It's weird has WebStorm is set up to sign by default my commits, I'll have a look back there then.
Would you agree we should close this PR waiting for me to do it back again with signed commits?

Thanks for your kind words.

**Comment by ivangabriele** [comment]
I just finished setting everything up in the CI so that your PRs can be checked automatically (fork PRs are treated differently than internal ones by Github for the sake of some valid [security concerns](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)).

**Comment by ivangabriele** [comment]
As for your PR, if you are motivated enough to learn how to [rebase](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase) and you know how to use `git reset`, you should be able to do that without leaving this PR by:

1. rebasing your branch locally on the last `main` branch commit
2. soft-resetting
3. create a new commit (with signature)
4. and force-pushing to this PR.

But you can also just recreate a PR if you're not used to this Git commands yet ;).

**Comment by dimitri-bourreau** [comment]
I had no idea I could rewrite on what's already's been pushed on a PR... thanks, I'll remember that. 👍
I do appreciate you took the time, I'm looking forward helping a little more on this repo. 🙂

**Comment by ivangabriele** [comment]
I'm happy to share :). And thanks a lot for the help!

You actually need to rebase this PR because, as you can see on the [Commits](https://github.com/betagouv/metiers-numeriques/pull/273/commits) tab, there are 14 other commits that have "diverged" from the main branch when they should only be one (`[docs(contributing): replace references to tell-me's repo with "metier…`). There is [an eternal debate between the "merging" and the "rebasing" strategies](https://www.atlassian.com/git/tutorials/merging-vs-rebasing#:~:text=Merging%20is%20a%20safe%20option,onto%20the%20tip%20of%20main%20.) but this repo is based on the rebasing one in order to keep a "linear" history of commits on the main branch (= a linear list of commits without any divergence), which makes it easier to read, understand and eventually rollback if there is an issue.

**Comment by dimitri-bourreau** [comment]
Hey @ivangabriele , thanks again. 👍
It does is a treat to contribute here with you.

**Pull request merged**
